"""Add default_tag to Ritual

Revision ID: 9117ecd69f4b
Revises: 8b2011cd83c9
Create Date: 2026-01-10 16:30:27.875098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9117ecd69f4b'
down_revision: Union[str, Sequence[str], None] = '8b2011cd83c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ritual', sa.Column('default_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ritual', 'default_tag')
    # ### end Alembic commands ###
